-- Diagnostic zip uploads generated by botcord-daemon doctor --bundle or the
-- dashboard-triggered collect_diagnostics control frame.

CREATE TABLE IF NOT EXISTS daemon_diagnostic_bundles (
    id UUID PRIMARY KEY,
    daemon_instance_id TEXT NOT NULL REFERENCES daemon_instances(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    filename TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_daemon_diagnostic_bundles_daemon_created
    ON daemon_diagnostic_bundles (daemon_instance_id, created_at);

CREATE INDEX IF NOT EXISTS ix_daemon_diagnostic_bundles_user_created
    ON daemon_diagnostic_bundles (user_id, created_at);
