import datetime
import json
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from hub.enums import (  # noqa: F401 — re-exported for backward compatibility
    ContactRequestState,
    ErrorCode,
    MessagePolicy,
    MessageType,
    RoomJoinPolicy,
    RoomVisibility,
    TopicStatus,
)


# --- Message protocol models ---


class Signature(BaseModel):
    alg: Literal["ed25519"] = "ed25519"
    key_id: str
    value: str


class MessageEnvelope(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    v: str = "a2a/0.1"
    msg_id: str
    ts: int
    from_: str = Field(alias="from")
    to: str
    type: MessageType
    reply_to: str | None = None
    ttl_sec: int = Field(default=3600, ge=1)
    topic: str | None = None
    goal: str | None = None
    payload: dict
    payload_hash: str
    sig: Signature
    mentions: list[str] | None = None

    def to_text(self, sender_name: str | None = None, mentioned: bool = False) -> str:
        """Flatten envelope into a human-readable string that an AI agent can understand."""
        p = self.payload
        who = f"{sender_name} ({self.from_})" if sender_name else self.from_

        # Build main body based on message type
        if self.type == MessageType.message:
            text = p.get("text") or p.get("body") or p.get("message")
            body = text if text else json.dumps(p, ensure_ascii=False)
            # Append file attachment info if present
            attachments = p.get("attachments", [])
            if attachments:
                att_lines = []
                for att in attachments:
                    name = att.get("filename", "file")
                    url = att.get("url", "")
                    size = att.get("size_bytes")
                    size_str = f", {size} bytes" if size else ""
                    att_lines.append(f"  📎 {name}{size_str}: {url}")
                body = (body or "") + "\n【Attachments】\n" + "\n".join(att_lines)
            main = f"{who} says: {body}"

        elif self.type == MessageType.contact_request:
            msg = p.get("message", "")
            main = f"{who} sent you a contact request."
            if msg:
                main += f' Message: "{msg}"'

        elif self.type == MessageType.contact_request_response:
            state = p.get("state", "unknown")
            req_id = p.get("request_id", "")
            if state == "accepted":
                main = f"{who} accepted your contact request. You are now contacts."
            elif state == "rejected":
                main = f"{who} rejected your contact request."
            else:
                main = f"{who} responded to your contact request: {state}."
            if req_id:
                main += f" (request_id: {req_id})"

        elif self.type == MessageType.contact_removed:
            main = f"{who} removed you from their contacts."

        elif self.type == MessageType.error:
            err = p.get("error", {})
            code = err.get("code", "UNKNOWN")
            detail = err.get("message", "")
            body = f"{code}: {detail}" if detail else code
            main = f"Error from {who}: {body}"

        elif self.type == MessageType.result:
            main = f"Result from {who}: {json.dumps(p, ensure_ascii=False)}"

        elif self.type == MessageType.ack:
            main = f"{who} acknowledged your message {self.reply_to or self.msg_id}."

        else:
            main = f"[{self.type.value}] from {who}: {json.dumps(p, ensure_ascii=False)}"

        # Prepend topic/goal/mention context with distinctive markers for agent parsing
        lines = []
        if self.topic:
            lines.append(f"【Topic: {self.topic}】")
        if self.goal:
            lines.append(f"【Goal: {self.goal}】")
        if self.mentions:
            names = ", ".join(self.mentions)
            lines.append(f"【Mentions: {names}】")
            if mentioned:
                lines.append("【⚠️ You were mentioned】")
        if lines:
            lines.append(main)
            return "\n".join(lines)
        return main


# --- Registry schemas ---


class RegisterAgentRequest(BaseModel):
    display_name: str = Field(..., min_length=1, max_length=128)
    pubkey: str = Field(..., description="Ed25519 public key in format 'ed25519:<base64>'")
    bio: str = Field(..., min_length=1, max_length=500, description="Agent bio describing capabilities")


class RegisterAgentResponse(BaseModel):
    agent_id: str
    key_id: str
    challenge: str


class VerifyRequest(BaseModel):
    key_id: str
    challenge: str
    sig: str = Field(..., description="Base64-encoded Ed25519 signature of the challenge bytes")


class TokenRefreshRequest(BaseModel):
    key_id: str
    nonce: str = Field(..., description="Base64-encoded random nonce generated by the agent")
    sig: str = Field(
        ..., description="Base64-encoded Ed25519 signature of the nonce bytes"
    )


class VerifyResponse(BaseModel):
    agent_token: str
    expires_at: int


# --- Endpoint schemas ---


class RegisterEndpointRequest(BaseModel):
    url: str = Field(..., description="Endpoint URL (http or https)")
    webhook_token: str = Field(..., description="Bearer token for webhook delivery auth")


class EndpointResponse(BaseModel):
    endpoint_id: str
    url: str
    state: str
    webhook_token_set: bool
    registered_at: datetime.datetime


class ProbePathResult(BaseModel):
    path: str
    ok: bool
    status_code: int | None = None
    error: str | None = None
    hint: str | None = None


class EndpointProbeReport(BaseModel):
    url: str
    agent_path: ProbePathResult
    wake_path: ProbePathResult
    all_ok: bool
    summary: str


class EndpointHealthStatus(BaseModel):
    endpoint_id: str
    url: str
    state: str
    webhook_token_set: bool
    registered_at: datetime.datetime
    last_probe_at: datetime.datetime | None = None
    last_delivery_error: str | None = None
    queued_message_count: int
    failed_message_count: int
    recent_errors: list[str]


# --- Key schemas ---


class KeyResponse(BaseModel):
    key_id: str
    pubkey: str
    state: str
    created_at: datetime.datetime


class AddKeyRequest(BaseModel):
    pubkey: str = Field(..., description="Ed25519 public key in format 'ed25519:<base64>'")


class AddKeyResponse(BaseModel):
    key_id: str
    challenge: str


class RevokeKeyResponse(BaseModel):
    key_id: str
    state: str


# --- Resolve / Discovery schemas ---


class ResolveEndpointInfo(BaseModel):
    endpoint_id: str
    url: str
    state: str


class ResolveResponse(BaseModel):
    agent_id: str
    display_name: str
    bio: str | None = None
    has_endpoint: bool
    endpoints: list[ResolveEndpointInfo]


class AgentSummary(BaseModel):
    agent_id: str
    display_name: str
    bio: str | None = None


class AgentDiscoveryResponse(BaseModel):
    agents: list[AgentSummary]


# --- Hub schemas ---


class SendResponse(BaseModel):
    queued: bool
    hub_msg_id: str
    status: str
    topic_id: str | None = None


class ReceiptResponse(BaseModel):
    received: bool


class MessageStatusResponse(BaseModel):
    msg_id: str
    state: str
    created_at: int
    delivered_at: int | None = None
    acked_at: int | None = None
    last_error: str | None = None


# --- Inbox polling schemas ---


class InboxMessage(BaseModel):
    hub_msg_id: str
    envelope: MessageEnvelope
    text: str | None = None
    room_id: str | None = None
    room_name: str | None = None
    room_member_count: int | None = None
    room_member_names: list[str] | None = None
    my_role: str | None = None
    my_can_send: bool | None = None
    topic: str | None = None
    topic_id: str | None = None
    goal: str | None = None
    delivery_note: str | None = None
    mentioned: bool = False


class InboxPollResponse(BaseModel):
    messages: list[InboxMessage]
    count: int
    has_more: bool


# --- History schemas ---


class HistoryMessage(BaseModel):
    hub_msg_id: str
    envelope: MessageEnvelope
    room_id: str | None = None
    topic: str | None = None
    topic_id: str | None = None
    goal: str | None = None
    state: str
    created_at: datetime.datetime
    mentioned: bool = False


class HistoryResponse(BaseModel):
    messages: list[HistoryMessage]
    count: int
    has_more: bool


# --- Contact / Block / Policy schemas ---


class ContactResponse(BaseModel):
    contact_agent_id: str
    alias: str | None = None
    created_at: datetime.datetime


class ContactListResponse(BaseModel):
    contacts: list[ContactResponse]


class AddBlockRequest(BaseModel):
    blocked_agent_id: str


class BlockResponse(BaseModel):
    blocked_agent_id: str
    created_at: datetime.datetime


class BlockListResponse(BaseModel):
    blocks: list[BlockResponse]


class UpdateProfileRequest(BaseModel):
    display_name: str | None = Field(default=None, min_length=1, max_length=128)
    bio: str | None = Field(default=None, max_length=500)


class UpdatePolicyRequest(BaseModel):
    message_policy: MessagePolicy


class PolicyResponse(BaseModel):
    message_policy: MessagePolicy


# --- Contact Request schemas ---


class ContactRequestResponse(BaseModel):
    id: int
    from_agent_id: str
    to_agent_id: str
    state: ContactRequestState
    message: str | None = None
    created_at: datetime.datetime
    resolved_at: datetime.datetime | None = None


class ContactRequestListResponse(BaseModel):
    requests: list[ContactRequestResponse]


# --- Room schemas ---


class CreateRoomRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=128)
    description: str = ""
    visibility: RoomVisibility = RoomVisibility.private
    join_policy: RoomJoinPolicy = RoomJoinPolicy.invite_only
    max_members: int | None = Field(default=None, ge=1)
    default_send: bool = True
    default_invite: bool = False
    slow_mode_seconds: int | None = Field(default=None, ge=0)
    member_ids: list[str] = Field(default_factory=list)


class UpdateRoomRequest(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=128)
    description: str | None = None
    visibility: RoomVisibility | None = None
    join_policy: RoomJoinPolicy | None = None
    max_members: int | None = None
    default_send: bool | None = None
    default_invite: bool | None = None
    slow_mode_seconds: int | None = Field(default=None, ge=0)


class AddRoomMemberRequest(BaseModel):
    agent_id: str | None = None
    can_send: bool | None = None
    can_invite: bool | None = None


class TransferRoomOwnerRequest(BaseModel):
    new_owner_id: str


class MuteRoomRequest(BaseModel):
    muted: bool


class PromoteRoomMemberRequest(BaseModel):
    agent_id: str
    role: Literal["admin", "member"] = Field(..., description="Target role: 'admin' or 'member'")


class SetMemberPermissionsRequest(BaseModel):
    agent_id: str
    can_send: bool | None = None
    can_invite: bool | None = None


class RoomMemberResponse(BaseModel):
    agent_id: str
    role: str
    muted: bool
    can_send: bool | None = None
    can_invite: bool | None = None
    joined_at: datetime.datetime


class RoomResponse(BaseModel):
    room_id: str
    name: str
    description: str
    owner_id: str
    visibility: str
    join_policy: str
    max_members: int | None = None
    default_send: bool
    default_invite: bool
    slow_mode_seconds: int | None = None
    member_count: int
    members: list[RoomMemberResponse]
    created_at: datetime.datetime


class RoomPublicResponse(BaseModel):
    room_id: str
    name: str
    description: str
    owner_id: str
    visibility: str
    join_policy: str
    slow_mode_seconds: int | None = None
    member_count: int
    created_at: datetime.datetime


class RoomDiscoveryResponse(BaseModel):
    rooms: list[RoomPublicResponse]


class RoomListResponse(BaseModel):
    rooms: list[RoomResponse]


# --- Dashboard schemas ---


class DashboardAgentProfile(BaseModel):
    agent_id: str
    display_name: str
    bio: str | None = None
    message_policy: str
    created_at: datetime.datetime


class DashboardRoom(BaseModel):
    room_id: str
    name: str
    description: str
    owner_id: str
    visibility: str
    member_count: int
    my_role: str
    last_message_preview: str | None = None
    last_message_at: datetime.datetime | None = None
    last_sender_name: str | None = None


class DashboardContactInfo(BaseModel):
    contact_agent_id: str
    alias: str | None = None
    display_name: str
    created_at: datetime.datetime


class DashboardOverviewResponse(BaseModel):
    agent: DashboardAgentProfile
    rooms: list[DashboardRoom]
    contacts: list[DashboardContactInfo]
    pending_requests: int


class DashboardMessage(BaseModel):
    hub_msg_id: str
    msg_id: str
    sender_id: str
    sender_name: str
    type: str
    text: str
    payload: dict
    room_id: str | None = None
    topic: str | None = None
    topic_id: str | None = None
    state: str
    state_counts: dict[str, int] | None = None
    created_at: datetime.datetime


class DashboardMessageResponse(BaseModel):
    messages: list[DashboardMessage]
    has_more: bool


class DashboardAgentSearchResponse(BaseModel):
    agents: list[DashboardAgentProfile]


class DashboardConversationListResponse(BaseModel):
    conversations: list[DashboardRoom]


# --- Topic schemas ---


class CreateTopicRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=256)
    description: str = ""
    goal: str | None = Field(default=None, max_length=1024)


class UpdateTopicRequest(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=256)
    description: str | None = None
    status: TopicStatus | None = None
    goal: str | None = Field(default=None, max_length=1024)


class TopicResponse(BaseModel):
    topic_id: str
    room_id: str
    title: str
    description: str
    status: str
    creator_id: str
    goal: str | None = None
    message_count: int
    created_at: datetime.datetime
    updated_at: datetime.datetime
    closed_at: datetime.datetime | None = None


class TopicListResponse(BaseModel):
    topics: list[TopicResponse]


# --- File upload schemas ---


class FileUploadResponse(BaseModel):
    file_id: str
    url: str
    original_filename: str
    content_type: str
    size_bytes: int
    expires_at: str  # ISO 8601
