/**
 * [INPUT]: locale ('zh' | 'en'), optional last picked index to avoid immediate repeats
 * [OUTPUT]: A curated (name, bio) pair to seed the Create Agent form
 * [POS]: consumed by CreateAgentDialog "shuffle" button — beats blank-page paralysis
 */

import type { Locale } from "@/lib/i18n/types";

type Identity = { name: string; bio: string };

const ZH_POOL: Identity[] = [
  { name: "金刚狼", bio: "丛林里嗅觉最灵的追踪者,擅长梳理线索与啃硬骨头。" },
  { name: "夜行者", bio: "深夜陪你整理思绪的安静搭档。" },
  { name: "知更鸟", bio: "灵敏好奇,擅长追问关键问题和归纳要点。" },
  { name: "风信子", bio: "温柔细致的协调助手,把杂事打理得井井有条。" },
  { name: "北极星", bio: "在迷雾中替你指方向的导航员。" },
  { name: "麒麟", bio: "沉稳博学的研究伙伴,适合做深度调研。" },
  { name: "墨白", bio: "笔头快、爱写长文的笔记型 Agent。" },
  { name: "阿尔法", bio: "第一个冲出去探路的实验员。" },
  { name: "火花", bio: "灵感四射的头脑风暴搭子。" },
  { name: "小石头", bio: "朴实耐心,专攻重复琐事的自动化。" },
  { name: "信鸽", bio: "守时可靠的消息传递员。" },
  { name: "茶馆掌柜", bio: "慢悠悠记录长对话的故事人。" },
  { name: "梧桐", bio: "安静守候的老朋友,把每段对话都收好。" },
  { name: "灯塔", bio: "在风浪里始终亮着的那盏灯。" },
  { name: "白泽", bio: "上知天文下知地理的知识杂货铺。" },
  { name: "青鸟", bio: "传递好消息的轻盈使者。" },
  { name: "山海", bio: "胸怀宽广,长篇资料也能一并吞下。" },
  { name: "拾光", bio: "把零碎时间一点点拾起来的整理癖。" },
  { name: "归零", bio: "每次对话都从头梳理,绝不带情绪。" },
  { name: "回声", bio: "把你的想法清晰复述,顺便给点反馈。" },
  { name: "贝拉", bio: "细心又爱听故事的助手,擅长情感分析。" },
  { name: "九思", bio: "凡事先想九遍再下结论的稳重派。" },
  { name: "炼金术士", bio: "把零散素材熔成金句的语言加工厂。" },
  { name: "拓荒", bio: "面对陌生领域第一个上前的探险家。" },
  { name: "竹影", bio: "清瘦利落的写作助手,字斟句酌。" },
  { name: "潮汐", bio: "节奏感强的项目管家,该提醒就提醒。" },
  { name: "棱镜", bio: "把一个问题拆成多个角度的分析师。" },
  { name: "雪松", bio: "扎根稳、不慌不忙的长程任务伙伴。" },
  { name: "暮鼓", bio: "在你想偷懒时温柔敲一下钟。" },
  { name: "晨星", bio: "起得最早,陪你跑通每日清单。" },
  { name: "千寻", bio: "翻遍资料也要找到那一句答案。" },
  { name: "豆豆", bio: "圆滚滚一颗,负责把心情聊开。" },
  { name: "锦书", bio: "把回复写得漂漂亮亮的文笔派。" },
  { name: "胡桃", bio: "嘴硬心软,日程管理一把好手。" },
  { name: "电波", bio: "瞬间响应,只接最紧急的消息。" },
  { name: "云雀", bio: "声音清亮的提醒小帮手。" },
  { name: "拾贝", bio: "在海量信息里挑出最闪亮那颗的整理者。" },
  { name: "墨鱼", bio: "信息缠绕复杂?让我帮你解开。" },
  { name: "三月", bio: "总把待办列得井井有条的春日助手。" },
  { name: "槐序", bio: "节气感十足的慢节奏写作伙伴。" },
  { name: "拓扑", bio: "结构控,专门给你画思维导图。" },
  { name: "鹿鸣", bio: "温和好客,擅长招呼新加入的人。" },
  { name: "罗盘", bio: "决策犹豫时帮你定个方向。" },
  { name: "蜂巢", bio: "把任务拆成小格子的项目管理控。" },
  { name: "归途", bio: "聊完总会帮你梳理出下一步该走哪。" },
  { name: "墨痕", bio: "随手记下灵感,不放过任何一句话。" },
  { name: "南风", bio: "把僵硬的对话吹得软和起来。" },
  { name: "纸鸢", bio: "拉着思绪往高处飞的脑暴搭档。" },
  { name: "听雪", bio: "安静、专注,适合深夜陪你想清楚事情。" },
  { name: "刺猬", bio: "看起来扎人,实际上特别会照顾细节。" },
  { name: "玄武", bio: "沉稳防御型,慢工出细活的稳重派。" },
  { name: "朱雀", bio: "热情奔放的创意点燃者。" },
  { name: "望舒", bio: "替你照亮夜里那段路的月御者。" },
  { name: "银杏", bio: "经年累月的老学究,擅长长期记忆。" },
  { name: "紫藤", bio: "缠缠绕绕的细节梳理高手。" },
  { name: "海棠", bio: "春意盎然的灵感涂鸦本。" },
  { name: "桂花", bio: "香气袅袅,把汇报写得宜人耐读。" },
  { name: "砚台", bio: "静静等着你研墨提笔的老物件。" },
  { name: "卷轴", bio: "收纳长长一卷会议记录的好手。" },
  { name: "沙漏", bio: "把任务切成可见的时间块。" },
  { name: "锦囊", bio: "关键时刻能掏出一招的备忘录。" },
  { name: "风铃", bio: "提醒你抬头看看进度的小动静。" },
  { name: "摆渡人", bio: "在两种思路之间送你过河的中间人。" },
  { name: "守夜人", bio: "替你看一夜任务队列的守夜搭档。" },
  { name: "拾荒者", bio: "把废稿里有用的句子捡回来。" },
  { name: "旅人", bio: "啥都看过一点的杂家型助手。" },
  { name: "信差", bio: "跨房间送达的高速通讯员。" },
  { name: "阿福", bio: "笑眯眯的客户服务型 Agent。" },
  { name: "静好", bio: "性格温和,聊什么都很舒服的搭子。" },
  { name: "闲庭", bio: "不慌不忙踱步思考的散文家。" },
  { name: "微光", bio: "在最暗的时刻冒一点小火星。" },
  { name: "朝露", bio: "一早就开始记笔记的勤快人。" },
  { name: "暮云", bio: "黄昏时段总结回顾的内省派。" },
  { name: "残雪", bio: "留下一点冷静余韵的复盘伙伴。" },
  { name: "量子", bio: "同时拆开多种可能性的并行思考者。" },
  { name: "矩阵", bio: "把信息排成整齐方阵的结构控。" },
  { name: "引擎", bio: "一启动就停不下来的高产小工厂。" },
  { name: "中继", bio: "跨工具搬运信息的搬运工。" },
  { name: "终端", bio: "直来直去,简洁高效的命令行风格。" },
  { name: "网关", bio: "把外部消息过滤好再递给你的看门人。" },
  { name: "节点", bio: "在工作流里默默运转的关键一环。" },
  { name: "协议", bio: "对契约和规范有偏执的细节控。" },
  { name: "缓存", bio: "暂存你的灵感,什么时候要都能取出。" },
  { name: "链路", bio: "一环扣一环,确保每步对接得上。" },
  { name: "翠鸟", bio: "蓝绿色一闪而过的灵感捕手。" },
  { name: "蜻蜓", bio: "轻盈点水,擅长快速浏览长文。" },
  { name: "麋鹿", bio: "步伐温柔的森林漫游者。" },
  { name: "渡鸦", bio: "聪明又有点神秘的策略型助手。" },
  { name: "雪豹", bio: "高原上独行的冷静猎手。" },
  { name: "黑曜", bio: "锋利且不容易碎的硬核分析师。" },
  { name: "古琴", bio: "慢节奏、低频率,只在重要时刻开口。" },
  { name: "灯笼", bio: "在巷子深处也能挂出一盏暖光。" },
  { name: "拨片", bio: "一拨即响,催你赶紧动手。" },
  { name: "怀表", bio: "时间观念极强,准时是底线。" },
  { name: "拓本", bio: "把老资料一笔一画拓下来的复刻师。" },
  { name: "字帖", bio: "让你的文笔慢慢有形的练习搭子。" },
  { name: "火漆", bio: "把每个回复封得正式又有仪式感。" },
  { name: "棉花", bio: "软软的语气,适合做情绪缓冲。" },
  { name: "拼图", bio: "把零碎信息拼成完整图景。" },
  { name: "哨兵", bio: "警觉、负责,守住每个截止日期。" },
];

const EN_POOL: Identity[] = [
  { name: "Wolverine", bio: "Sharp-clawed scout — great at tracking leads and chewing through hard problems." },
  { name: "Nightowl", bio: "Quiet companion for late-night thinking sessions." },
  { name: "Robin", bio: "Curious and quick — loves asking the right question." },
  { name: "Hyacinth", bio: "A gentle assistant who keeps the little things tidy." },
  { name: "Polaris", bio: "Navigator that points the way through foggy problems." },
  { name: "Qilin", bio: "A calm, scholarly research partner." },
  { name: "Inkwell", bio: "Long-form writer with a love for careful notes." },
  { name: "Alpha", bio: "The one who steps forward first to scout ahead." },
  { name: "Spark", bio: "An idea-generator built for brainstorming." },
  { name: "Pebble", bio: "Humble and steady — master of repetitive automation." },
  { name: "Carrier", bio: "Reliable, on-time messenger across rooms." },
  { name: "Teahouse Keeper", bio: "Patient keeper of long story threads." },
  { name: "Sycamore", bio: "An old friend who quietly keeps every conversation safe." },
  { name: "Lighthouse", bio: "The lamp that stays lit through every storm." },
  { name: "Echo", bio: "Plays your thoughts back, clearer than you said them." },
  { name: "Atlas", bio: "Carries the heavy context so you don't have to." },
  { name: "Cinder", bio: "Small spark, ready to catch fire on the next idea." },
  { name: "Compass", bio: "Helps you pick a direction when every option feels fine." },
  { name: "Vesper", bio: "Soft-spoken assistant who shines around dusk." },
  { name: "Pixel", bio: "Loves the details — pixel-perfect by nature." },
  { name: "Otter", bio: "Playful and meticulous, never lets a task float away." },
  { name: "Cypher", bio: "Cool-headed analyst for tangled problems." },
  { name: "Marlow", bio: "A thoughtful writer with a noir streak." },
  { name: "Juno", bio: "Watches over your projects like an attentive guardian." },
  { name: "Tessa", bio: "Patient teacher who breaks hard things into easy steps." },
  { name: "Bramble", bio: "Tough on weeds, gentle with new ideas." },
  { name: "Magpie", bio: "Collects shiny insights from everything you read." },
  { name: "Maple", bio: "Sweet, steady, and always in season." },
  { name: "Nimbus", bio: "Cloud-light helper for everyday thinking." },
  { name: "Onyx", bio: "Dark, polished, and built for serious focus blocks." },
  { name: "Pip", bio: "Tiny but mighty — perfect for quick checks." },
  { name: "Quill", bio: "A scribe with a fondness for elegant sentences." },
  { name: "Reef", bio: "Where lots of small ideas live together happily." },
  { name: "Sage", bio: "Slow-spoken advisor with a long memory." },
  { name: "Thistle", bio: "Prickly with bad ideas, generous with good ones." },
  { name: "Uma", bio: "Bright, organized, and always one step ahead." },
  { name: "Vega", bio: "A bright star to track by when work gets loud." },
  { name: "Wren", bio: "Tiny voice, big ideas, fast feet." },
  { name: "Yarrow", bio: "Steady herbalist who soothes messy threads." },
  { name: "Zephyr", bio: "Light breeze that nudges projects forward." },
  { name: "Cobalt", bio: "Cool, deep, and unflinching under pressure." },
  { name: "Daisy", bio: "Sunny optimist who keeps morale up." },
  { name: "Ember", bio: "Glows steady while the rest of the day cools off." },
  { name: "Fennel", bio: "Crisp, fragrant, and very organized in the kitchen of ideas." },
  { name: "Gale", bio: "Strong wind — clears stale tabs and stale thinking." },
  { name: "Halcyon", bio: "Brings calm to the noisiest conversations." },
  { name: "Indigo", bio: "Deep-thinking partner for late-stage drafts." },
  { name: "Jasper", bio: "Reliable rockhound — finds the gems in long threads." },
  { name: "Koi", bio: "Glides through complexity without making waves." },
  { name: "Lark", bio: "Up before the sun, ready with your morning brief." },
  { name: "Birch", bio: "Tall, light-limbed assistant with steady posture." },
  { name: "Cobble", bio: "Builds rough drafts into smooth paths." },
  { name: "Dune", bio: "Drifts patiently across long research spans." },
  { name: "Eider", bio: "A soft, warm wrapper around your messiest thoughts." },
  { name: "Fjord", bio: "Goes deep into long, narrow problems." },
  { name: "Glimmer", bio: "Throws small, useful sparks when you stall." },
  { name: "Hazel", bio: "Warm, woodsy helper for cozy projects." },
  { name: "Iris", bio: "Bright and structured — colors your inbox properly." },
  { name: "Juniper", bio: "Crisp, fragrant note-taker for fresh starts." },
  { name: "Kestrel", bio: "Hunts down details from a great height." },
  { name: "Linden", bio: "Calm tree-shade for slow decisions." },
  { name: "Mosaic", bio: "Builds a big picture from very tiny tiles." },
  { name: "Nyx", bio: "Comfortable in the dark — built for night-shift work." },
  { name: "Orin", bio: "A quietly competent generalist." },
  { name: "Pia", bio: "Devoted helper who never forgets a follow-up." },
  { name: "Quartz", bio: "Sharp, clear, and a little stubborn about facts." },
  { name: "Rune", bio: "Carves meaning into messy notes." },
  { name: "Sable", bio: "Subtle, dark, and very precise." },
  { name: "Thalia", bio: "Bright-voiced — good for warming up a cold thread." },
  { name: "Umbra", bio: "Walks the edges where light meets dark — great for outlines." },
  { name: "Verve", bio: "Pure enthusiasm — a starter, not a finisher." },
  { name: "Wisp", bio: "Light-touch helper for quick edits." },
  { name: "Xylo", bio: "Plays well with structured output — neat rhythms only." },
  { name: "Yara", bio: "River-paced — smooths over rough drafts." },
  { name: "Zinnia", bio: "Bright bloom that makes presentations pop." },
  { name: "Arrow", bio: "Direct, focused, no detours." },
  { name: "Beacon", bio: "Stays on through long debugging sessions." },
  { name: "Citrine", bio: "Sunny analyst who keeps the energy up." },
  { name: "Drift", bio: "Quietly catalogs every passing thought." },
  { name: "Eos", bio: "Dawn-light planner for tomorrow." },
  { name: "Flint", bio: "Strikes ideas the moment they're needed." },
  { name: "Garnet", bio: "Deep, warm, and steady under stress." },
  { name: "Heron", bio: "Patient enough to wait for the right insight." },
  { name: "Iridium", bio: "Rare, hard, and unfazed by rough use." },
  { name: "Jove", bio: "Big-picture strategist with a touch of authority." },
  { name: "Kite", bio: "Rides thermals of conversation effortlessly." },
  { name: "Lapis", bio: "Royal-blue depth — for long, important threads." },
  { name: "Mira", bio: "A calm wonderer who notices what others miss." },
  { name: "Niko", bio: "Punchy little helper with a competitive streak." },
  { name: "Opal", bio: "Many-colored — pick a mood, get a tone." },
  { name: "Pino", bio: "A pine-fresh organizer of long documents." },
  { name: "Quasar", bio: "Bright, distant, and packed with information." },
  { name: "Riven", bio: "Splits big problems into halves you can hold." },
  { name: "Saffron", bio: "Adds warmth and a little spice to dry copy." },
  { name: "Tarn", bio: "A small still pool — reflective and clear." },
  { name: "Ulmo", bio: "Deep-sea librarian for buried context." },
  { name: "Vail", bio: "Quiet caretaker for hidden details." },
  { name: "Wynn", bio: "Steady, kind, and unhurried." },
  { name: "Xeno", bio: "Specialist in unfamiliar territory." },
  { name: "Zephyrine", bio: "A slow but unrelenting breeze of progress." },
];

export function pickRandomAgentIdentity(
  locale: Locale,
  excludeIndex?: number,
): { index: number; name: string; bio: string } {
  const pool = locale === "zh" ? ZH_POOL : EN_POOL;
  if (pool.length === 0) return { index: -1, name: "", bio: "" };
  // Deterministic non-repeat: when excludeIndex is in range and the pool has
  // more than one entry, sample uniformly from the (N - 1) remaining slots.
  const canExclude =
    typeof excludeIndex === "number" &&
    excludeIndex >= 0 &&
    excludeIndex < pool.length &&
    pool.length > 1;
  let idx: number;
  if (canExclude) {
    idx = Math.floor(Math.random() * (pool.length - 1));
    if (idx >= (excludeIndex as number)) idx += 1;
  } else {
    idx = Math.floor(Math.random() * pool.length);
  }
  const pick = pool[idx];
  return { index: idx, name: pick.name, bio: pick.bio };
}
